---
- block: # Reboot host
  - name: Reboot target host
    shell: sleep 2 && shutdown -r now "Ansible triggered this reboot"
    async: 1
    poll: 0
    ignore_errors: true
    when: |
      host_need_reboot

  - name: Wait SSH to stopped
    become: false
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ ansible_port | default(22) }}"
      state: stopped
    delegate_to: 127.0.0.1
    when: |
      host_need_reboot

  - name: Wait to SSH again
    become: false
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ ansible_port | default(22) }}"
      timeout: "{{ host_reboot_timeout }}"
      state: started
      search_regex: OpenSSH
    delegate_to: 127.0.0.1
    when: |
      host_need_reboot

  tags:
    - host-tuning
    - host-rebooting
